### ISSUE TITLE
Add support for Visual Studio

### ISSUE THREAD

**Issue by dkrikun** [tailhook/quire#2]
MinGW build does not work too due too missing `obstack.h` :disappointed:

**Comment by tailhook** [comment]
You can get obstack.h from any BSD system (maybe freebsd). Just google for it. It's probably less useful to get obstack.h from linux(glibc) because presumably that will turn all your code into GPL.

Anyway, this code is not maintained any more. Sorry. The reason is that I don't write C any more. For low level system code I use rust (And there is a [similar library for rust](https://github.com/tailhook/rust-quire), although it's less powerful than C version yet)

**Comment by dkrikun** [comment]
Thanks for info
